version: "3.9"  # optional since v1.27.0
services:

  web_api:
    build: "./src/backend/ChatBotAI"
    container_name: chatbot-api
    depends_on:
      - sql
    ports:
      - "5055:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-server-2022
    ports: # not actually needed, because the two services are on the same network (required to access from localhost)
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password
      
  web:
    build: "./src/frontend/ChatBotAI"
    container_name: angular-app
    depends_on:
      - web_api
    ports:
      - "4201:4200"